"""add event_level_content table

Revision ID: 07038c554894
Revises: d1aa7e449b17
Create Date: 2026-08-12 18:24:05.301783

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07038c554894'
down_revision = 'd1aa7e449b17'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_level_content',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_slug', sa.String(length=64), nullable=False),
    sa.Column('level', sa.String(length=32), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('before', sa.Text(), nullable=False),
    sa.Column('during', sa.Text(), nullable=False),
    sa.Column('after', sa.Text(), nullable=False),
    sa.Column('narrative', sa.JSON(), nullable=False),
    sa.Column('why_it_matters', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['event_slug'], ['historical_events.slug'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_slug', 'level', name='uq_event_level')
    )
    with op.batch_alter_table('event_level_content', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_event_level_content_event_slug'), ['event_slug'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event_level_content', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_event_level_content_event_slug'))

    op.drop_table('event_level_content')
    # ### end Alembic commands ###
