"""add event_images table

Revision ID: 54539d6babe2
Revises: 07038c554894
Create Date: 2026-08-12 19:09:46.127942

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54539d6babe2'
down_revision = '07038c554894'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_slug', sa.String(length=64), nullable=False),
    sa.Column('image_type', sa.String(length=16), nullable=False),
    sa.Column('url', sa.String(length=1024), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('credit', sa.String(length=255), nullable=True),
    sa.Column('licence', sa.String(length=255), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['event_slug'], ['historical_events.slug'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_slug', 'image_type', name='uq_event_image_type')
    )
    with op.batch_alter_table('event_images', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_event_images_event_slug'), ['event_slug'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event_images', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_event_images_event_slug'))

    op.drop_table('event_images')
    # ### end Alembic commands ###
