"""add historical_events table and user.is_admin

Revision ID: d1aa7e449b17
Revises: cd575f175c03
Create Date: 2026-08-12 18:17:32.653963

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1aa7e449b17'
down_revision = 'cd575f175c03'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('historical_events',
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('day', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('date_label', sa.String(length=64), nullable=False),
    sa.Column('era', sa.String(length=64), nullable=False),
    sa.Column('era_key', sa.String(length=32), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=False),
    sa.Column('location_label', sa.String(length=255), nullable=True),
    sa.Column('map_pos_x', sa.Float(), nullable=True),
    sa.Column('map_pos_y', sa.Float(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('before', sa.Text(), nullable=False),
    sa.Column('during', sa.Text(), nullable=False),
    sa.Column('after', sa.Text(), nullable=False),
    sa.Column('narrative', sa.JSON(), nullable=False),
    sa.Column('why_it_matters', sa.Text(), nullable=False),
    sa.Column('characters', sa.JSON(), nullable=False),
    sa.Column('quiz_slug', sa.String(length=64), nullable=True),
    sa.Column('approximate', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('slug')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        # server_default is required here: the users table already has rows
        # in production (unlike a brand-new table), and Postgres rejects a
        # NOT NULL column added without one -- see the email_confirmed
        # rollout, which broke this exact way. Alembic autogenerate doesn't
        # add this by itself.
        batch_op.add_column(
            sa.Column('is_admin', sa.Boolean(), nullable=False, server_default=sa.false())
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('is_admin')

    op.drop_table('historical_events')
    # ### end Alembic commands ###
